from __future__ import annotations


ACTION_LABELS: dict[str, str] = {
    "wiggle": "Wiggle",
    "blink": "Blink",
    "fake_innocent_blink": "Fake innocent blink",
    "peek": "Peek",
    "scan": "Scan",
    "jump": "Jump",
    "flop": "Flop down",
    "melt": "Melt down",
    "dance": "Dance",
    "twirl": "Twirl",
    "stretch": "Stretch",
    "shake": "Shake",
    "happy_bounce": "Happy bounce",
    "nod": "Nod",
    "thinking_tilt": "Thinking tilt",
    "sleepy_sag": "Sleepy sag",
    "alarm_jolt": "Alarm jolt",
    "startled_pop": "Startled pop",
    "tail_wag": "Tail wag",
    "spin_jump": "Spin jump",
    "excited_spin": "Excited spin",
    "sneeze": "Sneeze",
    "shiver": "Shiver",
    "curious_lean": "Curious lean",
    "peekaboo": "Peekaboo",
    "zoomies": "Zoomies",
    "moonwalk": "Moonwalk",
    "pounce": "Pounce",
    "tail_idle_slow": "Tail slow sway",
    "tail_tip_flick": "Tail tip flick",
    "tail_smug_sway": "Tail smug sway",
    "tail_guilty_tuck": "Tail guilty tuck",
    "tail_sleepy_droop": "Tail sleepy droop",
    "tail_alert_snap": "Tail alert snap",
    "tail_frantic_innocent": "Tail frantic innocent",
    "tail_raise_excited": "Tail raise excited",
    "tail_question_hook": "Tail question hook",
    "tail_bristle": "Tail bristle",
    "inner_cover_oops": "Inner cover oops",
    "inner_side_smirk": "Inner side smirk",
    "inner_shy_retract": "Inner shy retract",
    "inner_droop": "Inner droop",
    "oops_innocent_combo": "Oops innocent combo",
    "britclip_enter": "Britclip suit-up",
    "britclip_exit": "Britclip suit-down",
    "tip_hat": "Tip hat",
    "bow_tie_check": "Bow tie check",
    "cane_tap": "Cane tap",
    "polite_bow": "Polite bow",
    "hat_tip_oops": "Hat tip oops",
    "paper_blanket": "Paper blanket",
    "paper_surfboard": "Paper surfboard",
    "paper_peek_curtain": "Paper peek curtain",
    "paper_fan": "Paper fan",
    "paper_whisper_fan": "Paper whisper fan",
    "paper_oops_cover": "Paper oops cover",
    "paper_tent": "Paper tent",
    "paper_pillow": "Paper pillow",
    "paper_stage": "Paper stage",
    "smug_sway": "Smug sway",
    "sulk": "Sulk",
    "hide": "Hide",
    "patrol": "Patrol",
    "celebrate": "Celebrate",
    "twist_scoot": "Twist scoot",
    "mini_hop_shift": "Mini hop shift",
    "relocate_hop": "Relocate hop",
    "roast_and_scoot": "Roast and scoot",
    "retreat_to_corner": "Retreat to corner",
    "drop_in": "Drop in",
    "tool_working": "Tool working",
    "paper_editing": "Paper editing",
    "waiting_stare": "Waiting stare",
    "permission_request": "Permission request",
    "paper_sorting": "Paper sorting",
    "reconnect_scan": "Reconnect scan",
    "error_autopsy": "Error autopsy",
    "thinking_loop": "Thinking loop",
}


# Chinese display names for the action menu. The ids stay language-independent;
# only what the menu SHOWS follows the language. English lives in ACTION_LABELS.
ACTION_LABELS_ZH: dict[str, str] = {
    "happy_bounce": "开心蹦跳",
    "dance": "跳舞",
    "celebrate": "庆祝",
    "excited_spin": "兴奋转圈",
    "smug_sway": "得意摇摆",
    "sulk": "委屈",
    "hide": "躲起来",
    "thinking_tilt": "歪头思考",
    "sleepy_sag": "犯困下沉",
    "alarm_jolt": "闹钟惊醒",
    "flop": "瘫倒",
    "melt": "融化",
    "stretch": "伸懒腰",
    "scan": "扫视",
    "patrol": "巡逻",
    "curious_lean": "好奇凑近",
    "shiver": "发抖",
    "wiggle": "扭一扭",
    "blink": "眨眼",
    "fake_innocent_blink": "装乖眨眼",
    "peek": "偷看",
    "jump": "跳跃",
    "spin_jump": "空翻跳",
    "twirl": "转身",
    "shake": "摇头",
    "sneeze": "打喷嚏",
    "peekaboo": "躲猫猫",
    "startled_pop": "吓一跳",
    "tail_wag": "摇尾巴",
    "tail_tip_flick": "尾尖轻甩",
    "tail_guilty_tuck": "心虚夹尾",
    "tail_alert_snap": "尾巴警觉",
    "nod": "点头",
    "tail_idle_slow": "尾巴慢摆",
    "tail_smug_sway": "得意摆尾",
    "tail_sleepy_droop": "尾巴垂落",
    "tail_frantic_innocent": "慌乱摆尾",
    "tail_raise_excited": "兴奋竖尾",
    "tail_question_hook": "疑问尾钩",
    "tail_bristle": "尾巴绷紧",
    "inner_cover_oops": "捂嘴糟糕",
    "inner_side_smirk": "内芯窃笑",
    "inner_shy_retract": "害羞缩回",
    "inner_droop": "内芯垂落",
    "oops_innocent_combo": "装无辜连招",
    "britclip_enter": "换上英伦装",
    "britclip_exit": "脱下英伦装",
    "tip_hat": "抬帽致意",
    "bow_tie_check": "整理领结",
    "cane_tap": "手杖轻点",
    "polite_bow": "礼貌鞠躬",
    "hat_tip_oops": "抬帽装傻",
    "paper_blanket": "纸被子",
    "paper_surfboard": "纸冲浪板",
    "paper_peek_curtain": "纸帘偷看",
    "paper_fan": "纸扇",
    "paper_whisper_fan": "纸扇密语",
    "paper_oops_cover": "纸挡脸",
    "paper_tent": "纸帐篷",
    "paper_pillow": "纸枕头",
    "paper_stage": "纸舞台",
    "thinking_loop": "持续思考",
    "tool_working": "工具运行",
    "paper_editing": "伏案修改",
    "paper_sorting": "纸张分类",
    "waiting_stare": "等待凝视",
    "permission_request": "请求许可",
    "reconnect_scan": "重连搜寻",
    "error_autopsy": "检查错误",
    "twist_scoot": "扭身挪动",
    "mini_hop_shift": "小跳挪位",
    "relocate_hop": "跳跃搬家",
    "zoomies": "疯跑",
    "moonwalk": "太空步",
    "pounce": "扑击",
    "roast_and_scoot": "吐槽就跑",
    "retreat_to_corner": "退到角落",
    "drop_in": "伞降登场",
}

MENU_GROUP_LABELS_ZH: dict[str, str] = {
    "Mood": "心情",
    "State": "姿态",
    "Reactive": "反应",
    "Tail": "尾巴",
    "Inner": "内芯",
    "Costume": "服装",
    "Paper Props": "纸道具",
    "Agent": "工作状态",
    "Movement": "移动",
}


def action_label(action_id: str, language: str = "zh-CN") -> str:
    """The action's menu name in the pal's language."""
    if str(language).startswith("en"):
        return ACTION_LABELS.get(action_id, action_id)
    return ACTION_LABELS_ZH.get(action_id, ACTION_LABELS.get(action_id, action_id))


def menu_group_label(group: str, language: str = "zh-CN") -> str:
    if str(language).startswith("en"):
        return group
    return MENU_GROUP_LABELS_ZH.get(group, group)

ACTION_MENU_GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Mood", ("happy_bounce", "dance", "celebrate", "excited_spin", "smug_sway", "sulk", "hide")),
    ("State", ("thinking_tilt", "sleepy_sag", "alarm_jolt", "flop", "melt", "stretch", "scan", "patrol", "curious_lean", "shiver")),
    ("Reactive", ("wiggle", "blink", "fake_innocent_blink", "peek", "jump", "spin_jump", "twirl", "shake", "sneeze", "peekaboo", "startled_pop", "tail_wag", "tail_tip_flick", "tail_guilty_tuck", "tail_alert_snap", "nod")),
    ("Tail", ("tail_idle_slow", "tail_smug_sway", "tail_sleepy_droop", "tail_frantic_innocent", "tail_raise_excited", "tail_question_hook", "tail_bristle")),
    ("Inner", ("inner_cover_oops", "inner_side_smirk", "inner_shy_retract", "inner_droop", "oops_innocent_combo")),
    ("Costume", ("britclip_enter", "britclip_exit", "tip_hat", "bow_tie_check", "cane_tap", "polite_bow", "hat_tip_oops")),
    ("Paper Props", ("paper_blanket", "paper_surfboard", "paper_peek_curtain", "paper_fan", "paper_whisper_fan", "paper_oops_cover", "paper_tent", "paper_pillow", "paper_stage")),
    ("Agent", ("thinking_loop", "tool_working", "paper_editing", "paper_sorting",
               "waiting_stare", "permission_request", "reconnect_scan", "error_autopsy")),
    ("Movement", ("twist_scoot", "mini_hop_shift", "relocate_hop", "zoomies", "moonwalk", "pounce", "roast_and_scoot", "retreat_to_corner", "drop_in")),
)

ACTION_DESCRIPTIONS: dict[str, str] = {
    "idle": "不做额外动作，保持轻微漂浮。",
    "bob": "很轻的点头/上下弹动，适合普通碎碎念。",
    "wiggle": "被戳或欠欠地抖一下，短促。",
    "blink": "轻轻眨一下眼，什么都不表示。",
    "fake_innocent_blink": "睁大眼睛左右偷看再装乖，是被抓包之后的表情。",
    "peek": "眼睛偷瞄鼠标或屏幕角落，适合观察。",
    "scan": "眼睛左右扫视，适合监控、找东西、读屏幕状态。",
    "jump": "明显跳一下，适合开心或突然来劲。",
    "flop": "整只纸夹趴下，适合累了、无语、放弃一秒。",
    "dance": "左右跳舞，适合得意、无聊自娱或庆祝。",
    "twirl": "2D 水平翻转转身，适合装酷或一本正经胡说八道。",
    "stretch": "伸懒腰，适合从 idle 醒来或准备开工。",
    "shake": "快速左右抖，适合紧张、报错、被吓到。",
    "happy_bounce": "轻快弹两下，适合开心、赞同、发现好事。",
    "nod": "点头，适合确认、假装懂了、认真附和。",
    "thinking_tilt": "歪着想一想，适合思考和吐槽前的停顿。",
    "sleepy_sag": "慢慢塌下去，眼皮越来越重，不会惊醒。适合困、无聊、加载太久。",
    "alarm_jolt": "打盹到一半被闹钟吵醒：瞳孔缩一下、惊慌、不耐烦，然后重新犯困。",
    "startled_pop": "突然弹高又缩回，适合被戳、提示、意外状态。",
    "tail_wag": "把回形针右侧翘起的尾端轻轻甩两下，适合开心、得意、被逗到。",
    "spin_jump": "跳起并在空中转体一整圈再落地，适合特别兴奋或想炫技。",
    "excited_spin": "原地快速转两圈然后骄傲亮相，适合按捺不住的激动。",
    "sneeze": "慢慢吸气仰起来，猛地打个喷嚏，再委屈地缓一下，适合灰尘、着凉、突发小事故。",
    "shiver": "缩起来发抖再慢慢平静，适合冷、害怕或看到可怕的代码。",
    "curious_lean": "好奇地朝一侧探身拉长凑近看，适合发现新东西或偷看屏幕。",
    "peekaboo": "迅速躲下去憋一会儿，再猛地弹出来，适合逗用户或装神秘。",
    "zoomies": "像猫发疯一样左右冲刺几趟带急刹，适合精力过剩。",
    "moonwalk": "面朝一边却往另一边滑走，滑到位再帅气转回来，适合得意退场。",
    "pounce": "压低身子扭两下蓄力，然后向前扑出一小段，适合盯上了什么东西。",
    "smug_sway": "得意地小幅左右摆，适合毒舌后装无辜。",
    "sulk": "缩下去闷一下，适合小委屈、小嫌弃、小无语。",
    "hide": "往下躲一躲，适合害羞、心虚、说完冷箭装无辜。",
    "patrol": "左右巡逻，适合等待、监控 Codex 或假装忙。",
    "celebrate": "更夸张的小庆祝，适合完成任务或状态变好。",
    "tool_working": "跑工具时的机械脉冲，节奏均匀、不移动，像进度在跳。",
    "paper_editing": "伏在纸面上逐行改，身体压低、小幅横向挪动。",
    "waiting_stare": "等人回话：几乎不动，只有一次极小的漂移和慢眨眼。",
    "permission_request": "凑近镜头把请求举起来并保持住，等一个答复。",
    "paper_sorting": "左右分堆，每一边都有一个放下的下沉动作。",
    "reconnect_scan": "来回搜寻信号，中间被两次卡顿打断。",
    "error_autopsy": "凑近并压低去看错误，停留很久，是审视不是惊慌。",
    "thinking_loop": "持续思考：两侧缓慢来回漂移，一直没有落定。",
}

ACTION_DESCRIPTIONS.update(
    {
        "tail_idle_slow": "Slow, low-intensity tail sway; use for quiet companionship and subtle aliveness.",
        "tail_tip_flick": "Quick tail-tip flick; use for impatience, suspicion, or a tiny opinion leaking out.",
        "tail_smug_sway": "Slow smug tail sway; use after a dry roast or when the pal is pleased with itself.",
        "tail_guilty_tuck": "Tail tucks inward; use for fake innocence, guilt, or pretending nothing happened.",
        "tail_sleepy_droop": "Tail droops softly; use for sleepy, bored, or waiting-too-long states.",
        "tail_alert_snap": "Tail snaps stiff then rebounds; use for warning, surprise, or sudden status changes.",
        "tail_frantic_innocent": "Short frantic tail betrayal; use when the pal is trying too hard to look innocent.",
        "tail_raise_excited": "尾巴竖直高举、梢部微颤，适合兴奋、打招呼、发现好事（猫式竖尾）。",
        "tail_question_hook": "尾巴弯成问号钩并保持，适合好奇、玩心起、歪着头研究东西。",
        "tail_bristle": "尾巴僵直炸起并快速震颤，适合防御、警戒、被吓到但摆出架势。",
        "melt": "Melt into a low readable puddle, hold for a beat, then recover; use for overload, embarrassment, or complete dramatic collapse.",
        "inner_cover_oops": "Inner core swings toward the face like a tiny oops/cover-mouth gesture; never open like a mouth.",
        "inner_side_smirk": "Inner core makes a small sideways smirk gesture; ambiguous between mouth-corner and hand.",
        "inner_shy_retract": "Inner core retracts inward like it has decided to stop incriminating itself.",
        "inner_droop": "Inner core droops softly for sleepy, sulky, or low-energy states.",
        "oops_innocent_combo": "Signature post-roast act: inner cover-oops, darting innocent eyes, frantic tail betrayal.",
        "britclip_enter": "Genderless British-inspired costume: tail produces a hat, bow tie, and cane, then holds the Britclip pose.",
        "britclip_exit": "Reverse the Britclip costume: cane away, bow tie folded, hat removed, then ordinary paperclip posture.",
        "tip_hat": "Tail-assisted hat tip for a polite oops or restrained English-mode acknowledgement.",
        "bow_tie_check": "Tiny costume-aware bow-tie adjustment; formal, neutral, and a little self-important.",
        "cane_tap": "Small cane tap for punctuation; restrained status or dry English-mode emphasis.",
        "polite_bow": "A tiny formal bow; courtesy without gendered body language.",
        "hat_tip_oops": "Tail-assisted hat tip/removal for an oops beat; use after a polite roast in English mode.",
        "paper_blanket": "Draft-paper blanket; use for sleepy, low-energy, or long-idle states.",
        "paper_surfboard": "Draft-paper surfboard; use for browser surfing, lively idle, or playful movement.",
        "paper_peek_curtain": "Draft-paper curtain with only the eyes showing; use for spying, waiting, or fake innocence.",
        "paper_fan": "Folded draft-paper fan; use for heat, stress, or dramatic unimpressed cooling.",
        "paper_whisper_fan": "Open draft-paper fan in front of the mouth/inner core; use for the sharpest spoken roast, like polite gossip after a lethal sentence.",
        "paper_oops_cover": "Draft paper held in front of the face; use after a roast or when pretending not to have said anything.",
        "paper_tent": "Folded draft-paper tent; use for hiding, focus retreat, or dramatic avoidance.",
        "paper_pillow": "Draft-paper pillow; use for sleepy or floppy low-energy beats.",
        "paper_stage": "Draft-paper stage mat; use for dance, celebration, or tiny performance moments.",
        "twist_scoot": "Small twist plus 10-20px scoot; frequent tiny reposition with attitude.",
        "mini_hop_shift": "Small hop shift of 20-50px with squash, arc, and rebound.",
        "relocate_hop": "Medium hop relocation with anticipation, landing squash, and rebound.",
        "roast_and_scoot": "Scoot away after a roast, then snap into fake innocence.",
        "retreat_to_corner": "Retreat toward a screen corner for quiet or self-restraint mode.",
        "drop_in": "Drop into the current station from above with a flat landing squash.",
    }
)

VISIBLE_ACTIONS: tuple[str, ...] = tuple(ACTION_LABELS)
MODEL_ACTIONS: tuple[str, ...] = ("idle", "bob", *VISIBLE_ACTIONS)
ACTION_SCHEMA_VALUE = "|".join(MODEL_ACTIONS)

# English action descriptions. These go straight into the model prompt, so a
# Chinese-only table used to push the model toward Chinese output even in
# English mode — which is what the `isascii()` guard in brain_ollama was
# papering over. Entries fall back to the Chinese text if one is missing.
ACTION_DESCRIPTIONS_EN: dict[str, str] = {
    "idle": "No extra motion; just keep floating slightly.",
    "bob": "A light nod or bounce; fine for ordinary muttering.",
    "wiggle": "A short shake after being poked, or out of cheek.",
    "blink": "A plain blink that means nothing on purpose.",
    "fake_innocent_blink": "Widen the eyes, glance either way, then play good — the face you make after being caught.",
    "peek": "Glance sideways at the cursor or a screen corner; good for observing.",
    "scan": "Sweep the eyes left and right; good for monitoring or reading state.",
    "jump": "A clear jump; good for delight or a sudden burst.",
    "flop": "Flop flat; good for tired, speechless, or giving up for a second.",
    "melt": "Melt into a readable puddle, hold, then recover; overload or full dramatic collapse.",
    "dance": "Bounce side to side; good for smug, self-amusement, or celebrating.",
    "twirl": "A horizontal flip spin; good for showing off or talking nonsense with a straight face.",
    "stretch": "A long stretch; good for waking from idle or getting ready to work.",
    "shake": "Fast side-to-side shaking; good for nervous, error, or startled.",
    "happy_bounce": "Two quick light bounces; good for happy, agreeing, or spotting good news.",
    "nod": "Nod; good for confirming or earnestly agreeing.",
    "thinking_tilt": "Tilt and think; good for a pause before a remark.",
    "sleepy_sag": "Sink slowly as the lids get heavy; nothing snaps back. For sleepy, bored, or a long wait.",
    "alarm_jolt": "Dozing until the alarm goes off: pupils shrink, panic, irritation, then drifting off again.",
    "startled_pop": "Pop up and shrink back; good for being poked or a sudden status change.",
    "tail_wag": "Wag the raised tail end twice; good for happy, smug, or being amused.",
    "smug_sway": "A small smug sway; good for playing innocent after a dry remark.",
    "sulk": "Shrink down and sulk; good for small grievances and mild disdain.",
    "hide": "Duck down; good for shy, guilty, or innocent after a cold remark.",
    "patrol": "Patrol side to side; good for waiting, monitoring, or looking busy.",
    "celebrate": "A bigger celebration; good for finishing a task or a status recovery.",
    "spin_jump": "Jump and spin a full turn in the air; good for extra excitement or showing off.",
    "excited_spin": "Spin twice on the spot then strike a proud pose; barely contained excitement.",
    "sneeze": "Inhale, sneeze hard, then recover sheepishly; dust, cold, or a small accident.",
    "shiver": "Curl up and tremble, then settle; cold, scared, or seeing frightening code.",
    "curious_lean": "Lean in and stretch toward one side to look closer; discovering something new.",
    "peekaboo": "Duck away, hold the suspense, then pop back out; teasing or being mysterious.",
    "zoomies": "Dash back and forth like a cat with the zoomies; too much energy.",
    "moonwalk": "Glide backwards facing the other way, then turn back; a smug exit.",
    "pounce": "Crouch, wiggle to charge, then leap forward; having spotted something.",
    "tail_idle_slow": "Slow, low-intensity tail sway; quiet companionship and subtle aliveness.",
    "tail_tip_flick": "Quick tail-tip flick; impatience, suspicion, or a small opinion leaking out.",
    "tail_smug_sway": "Slow smug tail sway; after a dry roast, or when pleased with itself.",
    "tail_guilty_tuck": "Tail tucks inward; fake innocence, guilt, or pretending nothing happened.",
    "tail_sleepy_droop": "Tail droops softly; sleepy, bored, or waiting too long.",
    "tail_alert_snap": "Tail snaps stiff then rebounds; warning, surprise, or a sudden status change.",
    "tail_frantic_innocent": "Short frantic tail betrayal; trying too hard to look innocent.",
    "tail_raise_excited": "Tail stands straight up with a quivering tip; excited, greeting, good news.",
    "tail_question_hook": "Tail curls into a question mark and holds; curious, playful, studying something.",
    "tail_bristle": "Tail goes rigid and trembles; defensive, on guard, spooked but posturing.",
    "inner_cover_oops": "Inner core swings toward the face like a small oops/cover gesture; never a mouth.",
    "inner_side_smirk": "Inner core makes a small sideways smirk gesture.",
    "inner_shy_retract": "Inner core retracts inward, having decided to stop incriminating itself.",
    "inner_droop": "Inner core droops softly for sleepy, sulky or low-energy states.",
    "oops_innocent_combo": "Signature post-roast act: inner cover-oops, darting innocent eyes, frantic tail.",
    "britclip_enter": "Britclip costume: the tail produces a hat, bow tie and cane, then holds the pose.",
    "britclip_exit": "Reverse the Britclip costume back to an ordinary paperclip posture.",
    "tip_hat": "Tail-assisted hat tip for a polite oops or a restrained acknowledgement.",
    "bow_tie_check": "A tiny costume-aware bow-tie adjustment; formal and a little self-important.",
    "cane_tap": "A small cane tap for punctuation; restrained status or dry emphasis.",
    "polite_bow": "A tiny formal bow; courtesy without gendered body language.",
    "hat_tip_oops": "Tail-assisted hat tip for an oops beat after a polite roast.",
    "paper_blanket": "Draft-paper blanket; sleepy, low-energy or long-idle states.",
    "paper_surfboard": "Draft-paper surfboard; browsing, lively idle or playful movement.",
    "paper_peek_curtain": "Draft-paper curtain with only the eyes showing; spying, waiting, fake innocence.",
    "paper_fan": "Folded draft-paper fan; heat, stress or dramatic unimpressed cooling.",
    "paper_whisper_fan": "Open fan in front of the inner core; the sharpest spoken roast, like polite gossip.",
    "paper_oops_cover": "Draft paper held in front of the face; after a roast, or pretending to have said nothing.",
    "paper_tent": "Folded draft-paper tent; hiding, focus retreat or dramatic avoidance.",
    "paper_pillow": "Draft-paper pillow; sleepy or floppy low-energy beats.",
    "paper_stage": "Draft-paper stage mat; dance, celebration or a tiny performance.",
    "twist_scoot": "A small twist plus a 10-20px scoot; a frequent tiny reposition with attitude.",
    "mini_hop_shift": "A small hop shift of 20-50px with squash, arc and rebound.",
    "relocate_hop": "A medium hop relocation with anticipation, landing squash and rebound.",
    "roast_and_scoot": "Scoot away after a roast, then snap into fake innocence.",
    "retreat_to_corner": "Retreat toward a screen corner for quiet or self-restraint mode.",
    "drop_in": "Descend into the current station from above under a paraglider canopy.",
    "tool_working": "An even mechanical pulse while a tool runs; no travel, like a progress tick.",
    "paper_editing": "Hunched over the page, stepping along a line with small sideways nudges.",
    "waiting_stare": "Waiting on a human: almost motionless, one tiny drift and a slow blink.",
    "permission_request": "Leans toward you, holds the ask up, and waits for an answer.",
    "paper_sorting": "Sorting into piles, with a set-down dip at each side.",
    "reconnect_scan": "Sweeping for a signal, interrupted twice by a stutter.",
    "error_autopsy": "Leans in and down over the error and stays there — scrutiny, not alarm.",
    "thinking_loop": "Sustained thought: drifting slowly to both sides, never settling.",
}


def action_descriptions(language: str = "zh-CN") -> dict[str, str]:
    """Action descriptions for a language, falling back per-key to Chinese."""
    if str(language).startswith("en"):
        return {name: ACTION_DESCRIPTIONS_EN.get(name, text)
                for name, text in ACTION_DESCRIPTIONS.items()}
    return ACTION_DESCRIPTIONS


def action_prompt(language: str = "zh-CN") -> str:
    """The action menu handed to the model, in the pal's current language."""
    return "\n".join(
        f"- {name}: {description}"
        for name, description in action_descriptions(language).items()
    )


ACTION_PROMPT = action_prompt("zh-CN")
